### ISSUE TITLE
Zurg config.yml overwritten 

### ISSUE THREAD

**Issue by jakeau** [I-am-PUID-0/pd_zurg#1]
**Describe the bug**

Each time the docker container restarts it overwrites the ./RD/config.yml file.

**To Reproduce**

Change any value in it or add an additional filter for 4k (What I was doing for 4k movies). Then restart config resets

**Expected behavior**

Changes made to the config file should be maintained. 

**Screenshots**

Nil

**Please complete the following information:**
 - OS: Ubuntu  Server
 - Version:  22.04 
 - Supporting Applications: Docker Compose

**Additional context**

Thanks for putting this together

**Comment by I-am-PUID-0** [comment]
Hi @jakeau,

Thanks for the feedback. That is the intended action. For a modified config.yml file to be used, it should be placed in the /config directory. 

      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup 
      - /pd_zurg/config:/config
      
The original reasoning for this process was to allow user selection for persisting any Zurg cached data, such as the Zurg process output to /zurg/RD/data or /zurg/RD/logs, by mapping or not, the /zurg/RD directory to the host. In other words, if a user does not map /zurg/RD to the host, then any Zurg cached data is cleared by restarting the container. 

I know none of this is clearly defined in the README or Wiki as of yet, but I hope to have those populated in the coming days. 

I do see how allowing modifications of the config.yml in the working directory -- /zurg/RD -- may be of benefit, so I'll reevaluate the current process for future implementation. I'm currently working on some major back-end changes to allow for automatic updates of the Zurg application, much like the automatic update of plex_debrid, so I won't be able to get to any process changes until that's released.

**Comment by codevski** [comment]
Thanks. This wasn't clear but copying the config file in RD into /config seems to have worked. Would this become a problem if you have both AD and RD active but with different settings (assuming they both use config.yml)

**Comment by I-am-PUID-0** [comment]
Update: As of Version [1.0.3], If a config.yml is found in the debrid directory -- /zurg/RD or /zurg/AD -- it will now be utilized and retain any changes previously made.
