### ISSUE TITLE
Requesting a guide for Windows Docker using WSL.

### ISSUE THREAD

**Issue by pranavkafle** [I-am-PUID-0/pd_zurg#19]
It would be great to have a way to deploy this in windows where docker is installed. This guide is Linux specific and many things are different for windows. Thanks!

**Comment by I-am-PUID-0** [comment]
A guide for WSL already exists in the Wiki: https://github.com/I-am-PUID-0/pd_zurg/wiki/Setup-Guides#windows-setup-guide-dockerwsl
