### ISSUE TITLE
Wrong variable rd_dir when using Alldebrid.

### ISSUE THREAD

**Issue by scobby** [I-am-PUID-0/pd_zurg#21]
**Describe the bug**

Wrong Variable in Sourcecode used

`Jan 23, 2024 10:23:52 - INFO - Setting up Zurg w/ AllDebrid instance in directory: /zurg/AD/
Jan 23, 2024 10:23:52 - ERROR - Error in Zurg setup: Exception: An error occurred during zurg setup - cannot access local variable 'rd_dir' where it is not associated with a value`

the variable rd_dir is used for alldebrid which is wrong, shoud be ad_dir.
Line 159 in setup.py 

**To Reproduce**

use of Alldebrid Account

**Expected behavior**

alldebrid account working

**Screenshots**

**Please complete the following information:**
not relevant.

**Additional context**

**Comment by I-am-PUID-0** [comment]
Thanks. I just pushed Version [2.0.4] to correct line 159. Give it about 30-40 minutes for the image to build and propagate to Docker Hub. Also, please note that I have not tested Zurg with AllDebrid, and I'm unsure if Zurg supports AllDebrid at this time.

**Comment by scobby** [comment]
@I-am-PUID-0 
thank you! that did the trick. now i have a new error:

`Jan 23, 2024 21:21:48 - INFO - Automatic update not required for plex_debrid
Jan 23, 2024 21:21:48 - ERROR - Zurg w/ AllDebrid subprocess:   **realdebrid**      Error when executing the user information request: api response error: bad_token (status code: 401) (code: 8)
Jan 23, 2024 21:21:48 - ERROR - Zurg w/ AllDebrid subprocess:   zurg    Failed to get user information: api response error: bad_token (status code: 401) (code: 8)
Jan 23, 2024 21:21:48 - ERROR - Zurg w/ AllDebrid subprocess:   **realdebrid**      Error when executing the get downloads request: api response error: bad_token (status code: 401) (code: 8)
Jan 23, 2024 21:21:48 - INFO - Zurg w/ AllDebrid subprocess: 2024-01-23T21:21:48.980+0100       FATAL   manager Cannot get downloads: api response error: bad_token (status code: 401) (code: 8)`


I think the program try to connect to real-debrid and not alldebrid.

**Comment by I-am-PUID-0** [comment]
Based on the Zurg GitHub repo, I don't believe AllDebrid is supported at this time: https://github.com/debridmediamanager/zurg-testing

However, the hooks are in place within pd_zurg to support AllDebrid if/when Zurg adds support. 

So, for now, only RealDebrid is supported with Zurg.

**Comment by scobby** [comment]
ah, ok that explains it. Just made an account on real-debrid and triening that.
