### ISSUE TITLE
RClone errors after zurg/RD/PD have been running for a while

### ISSUE THREAD

**Issue by Coast187** [I-am-PUID-0/pd_zurg#25]
**Describe the bug**

Errors regarding webdav and RClone in Docker logs, mount gets created but isn't populated with links. 

**To Reproduce**

Initially setup PlexDebrid with Plex, overseer and Real-Debrid. No changes made to config however it starts producing errors after about a day.
Yesterday I cleared the cache folder and uncommented some rclone lines in docker-compose.yml, everything worked for a day again.

**Expected behavior**

Continuous operation of underlying scripts

**Screenshots**

Please see attached logs
[docker log.txt](https://github.com/I-am-PUID-0/pd_zurg/files/14106938/docker.log.txt)
[docker-compose,yml.txt](https://github.com/I-am-PUID-0/pd_zurg/files/14106939/docker-compose.yml.txt)

**Please complete the following information:**
 - OS: Ubuntu 22.04 LTS, Docker CE 25.0.1, Portainer for stack staging

**Additional context**

Thank you!

**Comment by I-am-PUID-0** [comment]
Do you see this `INFO    zurg    Starting server on [::]:`  at any point?

It appears as though the Zurg process may not be fully loaded yet. 

A couple of things to try:

1. Disable all but the minimum rclone settings and wait till the above log entry is shown. Note the time it takes for the Zurg process to indicate the "Starting server" log entry. 
2. Revert to a previous release of Zurg with ` ZURG_VERSION=v0.9.2-hotfix.4`

**Comment by Coast187** [comment]
Commented out all rclone options, no change.
Version revert seems to have done it, many thanks!
