### ISSUE TITLE
Refresh seems to be broken / buggy

### ISSUE THREAD

**Issue by codevski** [I-am-PUID-0/pd_zurg#4]
**Describe the bug**

Refreshing Movie section seems to be completely bugged out. Movies are not being auto refreshed, trying to pin point the issue debugging it and ran into a couple of problems.

URL when its correct (using plex debrid to refresh) but the files dont get updated so plex skips it. Can take 2m + or if you cd and ls folder structure can occur sooner.

Using zurg plex_update.sh script is even worse the encoded path is wrong example:

url path
`torrents/movies/Indiana.Jones.And.The.Dial.Of.Destiny.2023.1080p.REMUX.ENG.ITA.LATINO.DTS-HD.Master.DDP5.1.MKV-BEN.THE.MEN.mkv`

should be url:
`torrents/movies/Indiana.Jones.And.The.Dial.Of.Destiny.2023.1080p.REMUX.ENG.ITA.LATINO.DTS-HD.Master.DDP5.1.MKV-BEN.THE.MEN/Indiana.Jones.And.The.Dial.Of.Destiny.2023.1080p.REMUX.ENG.ITA.LATINO.DTS-HD.Master.DDP5.1.MKV-BEN.THE.MEN.mkv`

constant ls you can see first and second attempt missing `kingdom of the crystal` movie and it eventually pops up and this is a good min after it appears in log that it was added.
<img width="1026" alt="Screenshot 2024-01-02 at 9 18 17 pm" src="https://github.com/I-am-PUID-0/pd_zurg/assets/1435321/cdb8826a-1587-4309-8e5c-f41a914f74fd">

**To Reproduce**

Add a movie in overseer 

**Expected behavior**

to update files in plex and when it refreshes the files to be there

**Screenshots**

<img width="1089" alt="image" src="https://github.com/I-am-PUID-0/pd_zurg/assets/1435321/46bd3a4b-826c-4abd-97db-a4ff762b3185">

**Please complete the following information:**
 - OS: docker
 - Version: latest
 - Supporting Applications: docker

**Additional context**

not sure if its a zurg issue because didnt get this with pdcrd  and the official way with just rclone_rd / plex-debrid

**Comment by I-am-PUID-0** [comment]
Feature added in Version [2.0.0]
