### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by skearney414** [I-am-PUID-0/pd_zurg#41]
**Describe the bug**

I am not sure if this is pd_zurg related or my own plex DB but I am gettin gthis error on latest image and on the latest version of plex Just wondering if you might know how to resolve? 

2024-02-23 12:29:29,513 (7f046776f808) :  DEBUG (streamservice:18) - Starting the stream service
2024-02-23 12:29:29,514 (7f046776f808) :  CRITICAL (runtime:709) - Private handlers are no longer supported; couldn't register <bound method StreamService.token_handler of <streamservice.StreamService object at 0x7f046372f990>>
2024-02-23 12:29:29,514 (7f0463f49b38) :  ERROR (networking:197) - Error opening URL 'http://127.0.0.1:32400/servers'

Note. this happens on the refreshing of plex by zurg after new content is added. 
**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - OS: [e.g., Ubuntu, Windows]
 - Version: [e.g., 22.04 LTS, WIN 11]
 - Supporting Applications: [e.g., Docker, Docker Desktop, WSL2]

**Additional context**

**Comment by I-am-PUID-0** [comment]
This appears to be a configuration issue with plex_debrid. Please share your setting for the environment variable `PLEX_ADDRESS=`

**Comment by skearney414** [comment]
It's http://192.168.1.110:32400 .. it was working previously. I actually ended up deleting my entire library last night and it works fine until I run plex debrid . If I set show menu to true it does not crash. I noticed the new docker image seemed to update some of the plex debrid config file. Can paste the whole configuration file if it helps

**Comment by skearney414** [comment]
The log is from plex logs which is why you see localhost as the url

**Comment by skearney414** [comment]
Believe it or not this was caused by plex labels being set as the update option on plex debrid. Looks like the latest version of plex doesn't like this.

**Comment by I-am-PUID-0** [comment]
Thanks for the update! I'm going to close this issue as it appears to be unrelated.
