### ISSUE TITLE
Docker Container Failure on Synology NAS - Invalid volume Specification

### ISSUE THREAD

**Issue by nobbylark** [I-am-PUID-0/pd_zurg#48]
Hi

Container is failing as it doesn't like "/data:shared" when using the value to set the location for the rclone mount to host. 

![image](https://github.com/I-am-PUID-0/pd_zurg/assets/80721162/23fa05be-a51f-4e11-934d-5d6df77992dc)

Any ideas? Sorry, I'm a bit of a noob !

**Comment by I-am-PUID-0** [comment]
Remove the `:rw` section.

**Comment by nobbylark** [comment]
That's the strange thing, I never added the `:rw` when setting up the volumes, only `/data:shared`.

**Comment by nobbylark** [comment]
I added the container without that volume so I wouldn't lose all the settings, etc. But before launching i tried to go back in and add the volume and get the following error:

![Screenshot_20240317_131436_DS finder](https://github.com/I-am-PUID-0/pd_zurg/assets/80721162/2e3b6e62-7383-4494-9af2-8c8b226d21e3)

**Comment by nobbylark** [comment]
I ran it via ssh and it worked
