### ISSUE TITLE
Zurg not downloading

### ISSUE THREAD

**Issue by robe718** [I-am-PUID-0/pd_zurg#5]
having an issue on loading the zurg portion of pd_zurg
getting the following error in PDZURG log
I *think* download.py (for zurg) is adding '-fix' to the name 'v0.9.2-hotfix.4-fix' when the release name should be 'v0.9.2-hotfix.4'
                                 
Jan  5, 2024 16:50:58 - INFO - Setting up Zurg
Jan  5, 2024 16:50:58 - INFO - 'ZURG_LOG_LEVEL' not set. Default log level INFO will be used.
Jan  5, 2024 16:50:58 - INFO - Configuring the debrid API key
Jan  5, 2024 16:50:58 - INFO - Setting up RealDebrid instance in directory: /zurg/RD/
Jan  5, 2024 16:50:58 - INFO - Fetching latest Zurg release.
Jan  5, 2024 16:50:58 - INFO - Zurg latest release: v0.9.2-hotfix.4-fix
Jan  5, 2024 16:50:59 - ERROR - Unable to download the file. Status code: 404
Jan  5, 2024 16:50:59 - ERROR - An error occurred: Failed to download and extract the release.

 - OS:Ubuntu
 - Version: 22.04 LTS
 - Supporting Applications: Docker, Docker Compose

**Comment by I-am-PUID-0** [comment]
What version of pd_zurg are you using? The issue should be resolved in Version [1.0.2].

**Comment by robe718** [comment]
My apologies, I pulled the latest image and right away this issue is fixed.
You are a gem! thank you for your prompt response and development of this project!
