### ISSUE TITLE
The docker container errors out when attempting to mount rclone with Error response from daemon: path /pd_zurg/mnt is mounted on / but it is not a shared mount

### ISSUE THREAD

**Issue by xcrailer** [I-am-PUID-0/pd_zurg#53]
When using docker on Ubuntu 22.04.4 LTS, I get the error Error response from daemon: path /pd_zurg/mnt is mounted on / but it is not a shared mount.

Can you please advise on how to fix this?

**Comment by I-am-PUID-0** [comment]
https://github.com/I-am-PUID-0/pd_zurg/wiki/FAQ#error-response-from-daemon-path-yourhostpathpdrcrdmnt-is-mounted-on--but-it-is-not-a-shared-mount
