### ISSUE TITLE
Error Unable to access the repository API issue?

### ISSUE THREAD

**Issue by Sunstealer1** [I-am-PUID-0/pd_zurg#54]
I have tried to get pd_zurg to initialize but I can't get it to work. Any idea where it is going wrong?
I have tried running it without specifying a network mode, using network_mode: host and assigning it to a network (it does not even get an ip?)

I am running Docker on an Orange Pi 5, Ubuntu 22.04.4 LTS.
I have created the following compose file in Portainer:
`version: "3.8"

services:
  pd_zurg:
    container_name: pd_zurg
    image: iampuid0/pd_zurg:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t

    volumes:
      ## Location of configuration files. If a Zurg config.yml and/or Zurg app is placed here, it will be used to override the default configuration and/or app used at startup. 
      - /data/docker-data/pd_zurg/config:/config
      ## Location for logs
      - /data/docker-data/pd_zurg/log:/log
      ## Location for rclone cache if enabled
      - /data/docker-data/pd_zurg/cache:/cache
      ## Location for Zurg RealDebrid active configuration
      - /data/docker-data/pd_zurg/RD:/zurg/RD
      ## Location for Zurg AllDebrid active configuration -- when supported by Zurg     
      - /data/docker-data/pd_zurg/AD:/zurg/AD
      ## Location for rclone mount to host
      - /data/docker-data/pd_zurg/mnt:/data:shared
    environment:
      - TZ=${TZ}
      ## Zurg Required Settings
      - ZURG_ENABLED=true
      - RD_API_KEY=${RD_API}
      ## Zurg Optional Settings
      - ZURG_LOG_LEVEL=DEBUG
     # - ZURG_VERSION=v0.9.2-hotfix.4
     # - ZURG_UPDATE=true
     # - PLEX_REFRESH=true
     # - PLEX_MOUNT_DIR=/pd_zurg 
     # - ZURG_USER=
     # - ZURG_PASS=
     # - ZURG_PORT=8800
      ## Rclone Required Settings
      - RCLONE_MOUNT_NAME=pd_zurg
      ## Rclone Optional Settings - See rclone docs for full list
     # - NFS_ENABLED=true
     # - NFS_PORT=8000
      - RCLONE_LOG_LEVEL=DEBUG
     # - RCLONE_CACHE_DIR=/cache
      - RCLONE_DIR_CACHE_TIME=10s
      - RCLONE_VFS_CACHE_MODE=full
      - RCLONE_VFS_CACHE_MAX_SIZE=80G
      - RCLONE_ATTR_TIMEOUT=1h
      - RCLONE_BUFFER_SIZE=32M
      - RCLONE_VFS_CACHE_MAX_AGE=4h
      - RCLONE_VFS_READ_CHUNK_SIZE=32M
      - RCLONE_VFS_READ_CHUNK_SIZE_LIMIT=1G
      - RCLONE_TRANSFERS=8
      ## Plex Debrid Required Settings
      - PD_ENABLED=true
      ## To utilize plex_debrid with Plex, the following environment variables are required
      - PLEX_USER=${PLEX_USER}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - PLEX_ADDRESS=${PLEX_ADDRESS}
      ## To utilize plex_debrid with Jellyfin, the following environment variables are required - Note that plex_debrid will require addtional setup befor use with Jellyfin
      - JF_ADDRESS=${JF_ADDRESS}
      - JF_API_KEY=${JF_API_KEY}
      ## Plex Debrid Optional Settings
     # - PD_UPDATE=true   
      - SHOW_MENU=true
      - SEERR_API_KEY=${SEERR_API_KEY}
      - SEERR_ADDRESS=${SEERR_ADDRESS}
      ## Special Features
     # - AUTO_UPDATE_INTERVAL=12
     # - DUPLICATE_CLEANUP=true
     # - CLEANUP_INTERVAL=1
      - PDZURG_LOG_LEVEL=DEBUG
     # - PDZURG_LOG_COUNT=2
    # Example to attach to gluetun vpn container if realdebrid blocks IP address 
    # network_mode: container:gluetun  
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN     
    security_opt:
      - apparmor:unconfined    
      - no-new-privileges
    #network_mode: host
    #networks:
    #  - frontend
    #  - backend
    #restart: unless-stopped`
`networks:
   frontend:
     external: true
   backend:
     external: true`

After composing up the container immediately exits and produces the following log:
Version: 2.1.5                                    

Jun 11, 2024 12:55:41 - INFO - Setting up Zurg

Jun 11, 2024 12:55:41 - DEBUG - Configuring the debrid API key for Zurg

Jun 11, 2024 12:55:41 - INFO - Setting up Zurg w/ RealDebrid instance in directory: /zurg/RD/

Jun 11, 2024 12:55:41 - DEBUG - System Architecture: aarch64, Operating System: Linux

Jun 11, 2024 12:55:41 - INFO - Fetching latest Zurg release.

Jun 11, 2024 12:55:41 - ERROR - Unable to access the repository API. Status code: 403

Jun 11, 2024 12:55:41 - ERROR - Error: Unable to access the repository API.

Jun 11, 2024 12:55:41 - ERROR - An error occurred: Failed to get the latest release version.

**Comment by I-am-PUID-0** [comment]
It looks like it may be a DNS or networking issue. Do you have Pihole or some other DNS filtering enabled? 
As a workaround, you can download the appropriate Zurg binary for your system here https://github.com/debridmediamanager/zurg-testing/releases/tag/v0.9.3-hotfix.11, then place the extracted zurg file in the `/data/docker-data/pd_zurg/RD` directory.

Also, you can only use Plex or Jellyfin, but not both simultaneously.
