### ISSUE TITLE
Way to use pd_zurg with Overseerr

### ISSUE THREAD

**Issue by bartje885** [I-am-PUID-0/pd_zurg#6]
**First of all, thanks for this project I really love it!**

**Is your feature request related to a problem? Please describe.**

As far as I know Plex Debrid is able to connect to Overseerr to request TV Shows and Movies so it's added to Debrid service

**Describe the solution you'd like**

Have switches to connect to Overseerr and configure Plex Debrid automatically

**Describe alternatives you've considered**

Configuring Plex Debrid manually within PD_Zurg, but I couldn't figure it out.

**Comment by I-am-PUID-0** [comment]
If plex_debrid is enabled and `SHOW_MENU=true`, then attach to the container and hit return/enter to access the plex_debrid UI. From there, you can configure Overseerr/Trakt and all other plex_debrid related settings. I will add Overseerr environment variables as an enhancement.

**Comment by bartje885** [comment]
Nice! Thanks for your quick response! Could be helpful if this is documented in the Wiki, or am I misreading this?

**Comment by I-am-PUID-0** [comment]
Feature added in Version [2.0.0]
