### ISSUE TITLE
Docker Compose fetches incorrect architechture binary on Raspbian arm64

### ISSUE THREAD

**Issue by spradeep** [I-am-PUID-0/pd_zurg#68]
**Describe the bug**

When setting up following this guide https://github.com/I-am-PUID-0/pd_zurg/wiki/Setup-Guides
the /zurg/RD/zurg binary is fetched of architecture instead of arm-hf instead of arm64

**To Reproduce**

Try on raspbian Linux raspberrypi 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Expected behavior**

Zurg fails to start

**Screenshots**

![Screenshot_20240825_230824](https://github.com/user-attachments/assets/e7421a04-aa11-41eb-a0f3-8e2c259fb0be)

**Please complete the following information:**
 - OS: Raspbian 12.6
 - Version: Linux raspberrypi 6.6.31+rpt-rpi-v8 
 - Supporting Applications: docker/portainer

**Additional context**

**Comment by I-am-PUID-0** [comment]
Currently tracking and characterizing this issue in the Discord server. Please try using `image: iampuid0/pd_zurg:2.7.0` until a fix is pushed.

**Comment by I-am-PUID-0** [comment]
Resolved w/ [Version [2.9.1]](https://github.com/I-am-PUID-0/pd_zurg/commit/c9a091146a345eb32ee514ca0c03973cff724ae3)
