### ISSUE TITLE
Dockerfile pulling the wrong zurg architecture, when running on aarch64

### ISSUE THREAD

**Issue by BrunoNFL** [I-am-PUID-0/pd_zurg#69]
**Describe the bug**

I'm running the script on a Oracle Cloud Instance on a Ampere A1 ARM VM.
When I deploy using Docker, it pulls the zurg ARMv7 binary, which doesn't run in it.
I had to manually download the ARM64 version, and replace in the pd_zurg/RD/ folder

**To Reproduce**

Deploy using Docker on a ARM64 machine

**Expected behavior**

I expected the script to download the correct version of the binary on its own.

**Screenshots**

N/A

**Please complete the following information:**
 - OS: Ubuntu ARM
 - Version: 22.04 LTS
 - Supporting Applications: Docker

**Additional context**

No other issues, after fixing this, the script runs perfectly!

**Comment by I-am-PUID-0** [comment]
Currently tracking and characterizing this issue in the Discord server. Please try using `image: iampuid0/pd_zurg:2.7.0` until a fix is pushed.

**Comment by I-am-PUID-0** [comment]
Resolved w/ [Version [2.9.1]](https://github.com/I-am-PUID-0/pd_zurg/commit/c9a091146a345eb32ee514ca0c03973cff724ae3)
