### ISSUE TITLE
Docker error with build 1.1.0

### ISSUE THREAD

**Issue by rbhr** [I-am-PUID-0/pd_zurg#7]
**Describe the bug**

Recreated pd_zurg container with the latest build on Docker Hub - 1.1.0 and now get this in the logs.

Traceback (most recent call last):
  File "/main.py", line 1, in <module>
    from base import *
  File "/base/__init__.py", line 2, in <module>
    from dotenv import load_dotenv, find_dotenv
ModuleNotFoundError: No module named 'dotenv'

**To Reproduce**
Run the latest docker build

**Expected behavior**
Container runs.

**Please complete the following information:**
 - OS: Ubuntu
 - Version: Ubuntu 22.04.3 LTS
 - Supporting Applications: Docker 24.0.7

**Comment by I-am-PUID-0** [comment]
Unfortunately, I'm unable to replicate the issue. 

A couple of options:

1. If you have not already done so, please try pulling the image again. 
2. Try to console into the container and provide the output of running `source /venv/bin/activate && pip list`

**Comment by rbhr** [comment]
I had re-pulled it a couple of times already and reverted to previous image which worked.
The 1.1.0 build is working now and pip list shows dotenv installed. I suspect it was a container networking problem.

Thanks for the response and thanks even more for the software!

**Comment by I-am-PUID-0** [comment]
Thanks for the feedback! 

As an aside, if you happen to be using Portianer, I have noted: On occasion, either the Stack will need to be stopped - if using stacks - or the container completely removed before changes are applied with a new image.
