### ISSUE TITLE
Any plans to transition to Riven? 

### ISSUE THREAD

**Issue by profucius** [I-am-PUID-0/pd_zurg#70]
With Plex_Debrid being defunct now, and Riven on the rise as a replacement, are there any plans to soon or eventually transition to Riven in the docker container? 

I'm a bit apprehensive with docker as a novice to the environment, so your repo has helped me a lot. I'd love to start using Riven instead of PD so that I can start using its features now and as they continue to develop. What are your thoughts?

**Comment by I-am-PUID-0** [comment]
There's already a new project using Riven; DMB: https://github.com/I-am-PUID-0/DMB

**Comment by profucius** [comment]
I somehow missed this, cheers!
