### ISSUE TITLE
pd_zurg

### ISSUE THREAD

**Issue by mladeen1988** [I-am-PUID-0/pd_zurg#81]
**Describe the bug**

plex debrid gives error when trying to run after whole setup.All elese is working but cand request new movies from seer or plex.
plex working,rclone mounting is ok,seer working,all tokens are ok.

**To Reproduce**

Steps to reproduce the behavior.
normal installation following guide

**Expected behavior**
start to pickup titles from requested media

**Please complete the following information:**
 - OS: Ubuntu
 - Version: docker-compose

here is portion of error from pd_zurg console and its not stoping:
Nov 13, 2024 18:24:27 - INFO - plex_debrid: request error: HTTPSConnectionPool(host='torrentio.strem.fun', port=443): Max retries exceeded with url: /sort=qualitysize%7Cqualityfilter=480p,scr,cam/stream/series/tt2562232:1:1.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7cddbf49a490>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by I-am-PUID-0** [comment]
Torrentio is down

**Comment by mladeen1988** [comment]
> Torrentio is down

Yeah…sorry
