### ISSUE TITLE
Torrentio doesn't find any release anymore.

### ISSUE THREAD

**Issue by dariokan82** [I-am-PUID-0/pd_zurg#85]
Since the RD shenanigans of the past weeks, my pd_zurg deployment cannot find any release via torrentio.

If I add it to my RD via Debrid Media Manager, then it sees it and adds it.

Any clue how to fix this?

MAny thanks

**Comment by FreakSigns** [comment]
I am seeing the same issue. This might be related to the outdated torrentio file. The other plex_debrid forks did update it within the last week.

**Comment by I-am-PUID-0** [comment]
Try pulling the latest pd_zurg image; it should have the latest elfhosted version of plex_debrid.

**Comment by FreakSigns** [comment]
I updated but still the same with 0 finds on torrentio. Looks like it’s happening on plex-debrid as well based on a post in discord.

**Comment by FreakSigns** [comment]
Based on a comment in discord, torrentio needs a user agent now in the request. But the elf fork should have those changes, still seeing the same issue: 
`Dec  8, 2024 22:42:46 - INFO - plex_debrid subprocess: [08/12/24 22:42:41] scraping sources [torrentio] for query "its.a.wonderful.life.1946" ... done - found 0 releases
Dec  8, 2024 22:42:56 - INFO - plex_debrid subprocess: [08/12/24 22:42:46] scraping sources [torrentio] for IMDB ID "tt0038650" ... done - found 0 releases
Dec  8, 2024 22:43:06 - INFO - plex_debrid subprocess: [08/12/24 22:42:56] scraping sources [torrentio] for query "its.a.wonderful.life.1945" ... done - found 0 releases
Dec  8, 2024 22:43:16 - INFO - plex_debrid subprocess: [08/12/24 22:43:06] scraping sources [torrentio] for query "its.a.wonderful.life.1947" ... done - found 0 releases
`

**Comment by I-am-PUID-0** [comment]
Try using `PD_REPO=mercuryy-1337,plex_debrid,main`

**Comment by FreakSigns** [comment]
*UPDATE* Fixed it by disabling PD_UPDATE=false 

Thanks for the follow up. 
My plex_debrid version is somehow on v2.97 but mercuryy is on v2.96 and therefore no update is installed. 

`Dec  9, 2024 12:41:44 - INFO - Checking for available plex_debrid updates
Dec  9, 2024 12:41:44 - DEBUG - Repository: mercuryy-1337/plex_debrid branch: main, being used for plex_debrid
Dec  9, 2024 12:41:44 - DEBUG - Repository URL for plex_debrid update: https://github.com/mercuryy-1337/plex_debrid/archive/refs/heads/main.zip
Dec  9, 2024 12:41:44 - DEBUG - Settings URL for plex_debrid update: https://raw.githubusercontent.com/mercuryy-1337/plex_debrid/main/ui/ui_settings.py
Dec  9, 2024 12:41:44 - INFO - Currently installed version of plex_debrid: [v2.97]
`
`Dec  9, 2024 12:41:44 - INFO - Latest version of plex_debrid: [v2.96]
Dec  9, 2024 12:41:44 - INFO - Automatic update not required for plex_debrid`

**Comment by j-azzopardi** [comment]
getting the same issue. can someone explain how to change the pd version used to mercuryy repo?

**Comment by dariokan82** [comment]
If you are using docker, you have to recreate your container and add the following variables:

PD_REPO=mercuryy-1337,plex_debrid,main

Once recreated with these parameters, it should work. I don't know the instructions for other installations I'm afraid!

I'm testing it today for myself and should that work I'll close the issue.

EDIT: Make sure you # PD_UPDATE=true so that the correct repo will download. I had the same issue as @FreakSigns

**Comment by dariokan82** [comment]
Adding the line:

`PD_REPO=mercuryy-1337,plex_debrid,main`

To the docker-compose.yml and recreating the container fixed the issue. Thanks everyone!

**Comment by dariokan82** [comment]
UPDATE: while using the mercury repo and fundamentally PD 2.96 works, the CPU usage creeps up until it finally gets to 150% and I have to kill the container. 

I tried to recreate it with CPU limitations, but it happens regardless.

I'd love to jump over to Riven (DMB), but for the life of me I couldn't set that one up. So I guess I'm stuck :)

**Comment by I-am-PUID-0** [comment]
I updated the files in the default plex_debrid to the latest provided by Elfhosted. [Version [2.9.2]](https://github.com/I-am-PUID-0/pd_zurg/commit/7e32c7fa1f64c2d0600cfbaa69375e2910920c54)

**Comment by dariokan82** [comment]
thanks. I took this as a sign to plunge and moved to DMB with Riven, so I'll close the issue!
