### ISSUE TITLE
Can you add links parameter to allow sym links?

### ISSUE THREAD

**Issue by Q-efx** [I-am-PUID-0/pd_zurg#9]
Its a starting parameter for rclone :)

**Comment by I-am-PUID-0** [comment]
Can you describe the request in more detail? 

Is it something that can be facilitated with: https://github.com/I-am-PUID-0/pd_zurg/wiki#rclone-flags-passed-via-docker-environment-variable

**Comment by Q-efx** [comment]
Oh didnt know!
So, to add --links parameter, I would need to add RCLONE_LINKS?

**Comment by Q-efx** [comment]
Hmm added it...

      - RCLONE_LINKS
      - RCLONE_COPY_LINKS
That should work right?

But I cant create symlinks. I guess its too many system layered on each other :(

**Comment by nbn22385** [comment]
> Hmm added it...

Not sure if you will get behavior you are after, [rclone docs](https://rclone.org/local/#symlinks-junction-points) say `--copy-links` is not compatible with `--links` when used together.
